bug_tracker_v2/tracker/urls.py
from django.urls import path
from . import views

app_name = 'tracker'

urlpatterns = [
    path('tickets/', views.TicketTable.as_view(), name='ticket_list'),
    path('tickets/closed/', views.ClosedTicketTable.as_view(), name='closed_ticket_list'),
    path('tickets/assigned/', views.AssignedTicketTable.as_view(), name='assigned_ticket_list'),
    path('tickets/assigned/closed/', views.ClosedAssignedTicketTable.as_view(), name='closed_assigned_ticket_list'),
    path('tickets/create/', views.CreateTicket.as_view(), name='create_ticket'),
    path('tickets/<pk>/', views.SuperTicketDetails.as_view(), name='ticket_details'),
    path('tickets/<pk>/update', views.UpdateTicket.as_view(), name='ticket_update'),
    path('tickets/<pk>/subscribe/', views.SubscribeTicketView.as_view(), name='subscribe_ticket'),
    path('tickets/<pk>/unsubscribe/', views.UnsubscribeTicketView.as_view(), name='unsubscribe_ticket'),
    path('projects/', views.ProjectTable.as_view(), name='project_list'),
    path('projects/archived/', views.ArchivedProjectTable.as_view(), name='archived_project_list'),
    path('archive-project/<project_pk>/', views.ToggleArchiveProject.as_view(), name='archive_project'),
    path('projects/<project_pk>/', views.ProjectDetails.as_view(), name='project_details'),
    path('projects/<project_pk>/update', views.UpdateProject.as_view(), name='project_update'),
    path('projects/<project_pk>/manage-developers/', views.ProjectManageDevelopers.as_view(), name='project_manage_developers'),
    path('projects/<project_pk>/closed_tickets', views.ProjectDetailsClosedTickets.as_view(), name='project_details_closed_tickets'),
    path('projects/<project_pk>/subscribe_to_all/', views.ProjectSubscribeAllTicketsView.as_view(), name='subscribe_all'),
    path('projects/<project_pk>/unsubscribe_to_all/', views.ProjectUnsubscribeAllTicketsView.as_view(),
         name='unsubscribe_all'),
    path('projects/create', views.CreateProject.as_view(), name='create_project'),
    path('delete-comment/<pk>/', views.CommentDelete.as_view(), name='delete_comment'),
    ### Team-related URLs
    path('team_details/', views.TeamDetails.as_view(), name='team_details'),
    path('update/', views.TeamUpdateView.as_view(), name='team_update'),
]

bug_tracker_v2/users/urls.py
from django.urls import path

from bug_tracker_v2.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from .home_view import HomePage
from bug_tracker_v2.tracker.views import (
    TeamDetails, TeamListView, TeamCreateView, TeamAddManager, AcceptTeamInvitation, SendTeamInvitation,
    ManageSubscriptions, MultipleUnsubscribeView, InvitationsListView, DeclineTeamInvitation, ManageNotificationSettings,
    EnableNotificationSetting, DisableNotificationSetting, TeamRemoveManager, TeamAddOwner, ManageTeamOwnership,
    ManageTeamOwnershipWarning, TeamRemoveOwner, TeamRemoveMember, LeaveTeam,
)

from django.urls import reverse

urlpatterns = [
    # path("", HomePage.as_view(), name="home"),
    path("", TeamListView.as_view(), name='home'),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("bug_tracker_v2.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('teams/<slug:team_slug>/', TeamDetails.as_view(), name='team_details'),
    path('teams/<slug:team_slug>/', include('bug_tracker_v2.tracker.urls', namespace='tracker')),
    path('teams/', TeamListView.as_view(), name='team_list'),
    path('create-team/', TeamCreateView.as_view(), name='team_create'),
    path('teams/<slug:team_slug>/leave-team/', LeaveTeam.as_view(), name='leave_team'),
    path('teams/<slug:team_slug>/add-manager/', TeamAddManager.as_view(), name='team_add_manager'),
    path('teams/<slug:team_slug>/remove-manager/', TeamRemoveManager.as_view(), name='team_remove_manager'),
    path('teams/<slug:team_slug>/warning/', ManageTeamOwnershipWarning.as_view(), name='team_ownership_warning'),
    path('teams/<slug:team_slug>/manage-ownership/', ManageTeamOwnership.as_view(), name='manage_team_ownership'),
    path('teams/<slug:team_slug>/add-owner/', TeamAddOwner.as_view(), name='team_add_owner'),
    path('teams/<slug:team_slug>/remove-owner/', TeamRemoveOwner.as_view(), name='team_remove_owner'),
    path('teams/<slug:team_slug>/remove-member/', TeamRemoveMember.as_view(), name='remove_team_member'),
    path('teams/<slug:team_slug>/invite/', SendTeamInvitation.as_view(), name='team_invite'),
    path('accept-invitation/', AcceptTeamInvitation.as_view(), name='accept_team_invitation'),
    path('decline-invitation/', DeclineTeamInvitation.as_view(), name='decline_team_invitation'),
    path('pending-invitations/', InvitationsListView.as_view(), name='pending_invitations'),
    path('my-subscriptions/', ManageSubscriptions.as_view(), name='manage_subscriptions'),
    path('manage-notifications/', ManageNotificationSettings.as_view(), name='manage_notifications'),
    path('disable-notifications/', DisableNotificationSetting.as_view(), name='disable_notification'),
    path('enable-notifications/', EnableNotificationSetting.as_view(), name='enable_notification'),
    path('multiple-unsubscribe/', MultipleUnsubscribeView.as_view(), name='multiple_unsubscribe'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "error-400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "error-403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "error-404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("error-500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bug_tracker_v2/tracker/models.py
import uuid
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.utils.html import mark_safe
from django.core import paginator, mail
from django.core.exceptions import ValidationError
from markdown import markdown

from .model_validators import ContentTypeRestrictedFileField
from .signals import unique_slug_generator
from .constants import NOTIFICATION_SETTING_DEFAULTS

User = get_user_model()


class ProjectQueryset(models.QuerySet):
    def filter_for_team_and_user(self, team_slug, user):
        team = Team.objects.get(slug=team_slug)
        if user in team.get_owners():
            return self.filter(team__slug=team_slug)
        else:
            return self.filter(Q(team__slug=team_slug), Q(manager=user)|Q(developers=user))


class TicketQueryset(models.QuerySet):
    def filter_for_team_and_user(self, team_slug, user):
        team = Team.objects.get(slug=team_slug)
        if user in team.get_owners():
            return self.filter(team__slug=team_slug)
        else:
            return self.filter(Q(team__slug=team_slug), Q(project__manager=user)|Q(project__developers=user))


# owned_teams = models.Team.objects.filter(memberships__role=3, memberships__user=self.request.user).order_by('title')

class TeamQueryset(models.QuerySet):
    def user_owned_teams(self, user):
        return self.filter(memberships__role=3, memberships__user=user)

    def user_managed_teams(self, user):
        return self.filter(memberships__role=2, memberships__user=user)

    def user_member_teams(self, user):
        return self.filter(memberships__role=1, memberships__user=user)


class Team(models.Model):
    title = models.CharField(unique=True, max_length=255)
    description = models.TextField()
    members = models.ManyToManyField(User, related_name='teams', blank=True, through='TeamMembership')
    slug = models.SlugField(unique=True)

    objects = models.Manager.from_queryset(TeamQueryset)()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('team_details', kwargs={'team_slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = self.slug or unique_slug_generator(self)
        super().save(*args, **kwargs)

    def get_description_as_markdown(self):
        return mark_safe(markdown(self.description, extensions=['codehilite', 'fenced_code']))

    def get_managers(self):
        return self.members.filter(memberships__role=2)

    def get_owners(self):
        return self.members.filter(memberships__role=3)

    def get_only_members(self):
        return self.members.filter(memberships__role=1)

    def add_owner(self, user):
        if user in self.get_managers() or user in self.get_only_members():
            membership = user.memberships.get(user=user, team=self)
            membership.role = 3
            membership.save()

    def remove_owner(self, user):
        if self.get_owners().count() > 1:
            if user in self.get_owners():
                membership = user.memberships.get(user=user, team=self)
                membership.role = 1
                membership.save()
                return True
        return False

    def add_manager(self, user):
        if user in self.get_only_members():
            membership = user.memberships.get(user=user, team=self)
            if membership.role != 3:
                membership.role = 2
                membership.save()

    def remove_manager(self, user):
        if user in self.get_managers():
            membership = user.memberships.get(user=user, team=self)
            if membership.role != 3:
                membership.role = 1
                membership.save()
                self.projects.filter(manager=user).update(manager=None)

    def remove_member(self, user):
        if user in self.members.all() and user not in self.get_owners():
            membership = user.memberships.get(user=user, team=self)
            if membership.role == 2:
                self.projects.filter(manager=user).update(manager=None)
            Project.developers.through.objects.filter(project__in=self.projects.all(), user=user).delete()
            Ticket.developer.through.objects.filter(ticket__team=self, user=user).delete()
            membership.delete()

    def get_users_role(self, user):
        membership = user.memberships.get(user=user, team=self)
        return membership.role


class TeamMembership(models.Model):

    MEMBER = 1
    MANAGER = 2
    OWNER = 3

    ROLES = (
        (MEMBER, "Member",),
        (MANAGER, "Manager",),
        (OWNER, "Owner",),
            )

    team = models.ForeignKey(Team, on_delete=models.CASCADE, db_column='team_id', related_name='memberships')
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_column='user_id', related_name='memberships')
    role = models.IntegerField(choices=ROLES, default=MEMBER)

    class Meta:
        db_table = 'tracker_team_members'
        unique_together = ('user', 'team',)

    def __str__(self):
        return f'{self.user}-{self.team}'


class TeamInvitation(models.Model):
    PENDING = 1
    ACCEPTED = 2
    DECLINED = 3

    STATUSES = (
        (PENDING, 'Pending',),
        (ACCEPTED, 'Accepted',),
        (DECLINED, 'Declined',),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    invitee = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)
    invitee_email = models.EmailField()
    # is_accepted = models.BooleanField(default=False)
    created_on = models.DateField(auto_now_add=True, editable=False)
    status = models.IntegerField(choices=STATUSES, default=PENDING)

    def send_email(self, inviter, team, invitation_uuid):
        domain = get_current_site(request=None).domain
        message_text = f"""You have been invited to join {team} by {inviter}.
If you are already registered, click this link to accept this invitation: https://{domain}{(reverse('accept_team_invitation'))}?invitation={invitation_uuid}.
If you are not registered, click this link to register first: https://{domain}/accounts/signup."""
        mail.send_mail(
            subject='Team Invitation',
            message=message_text,
            from_email='noreply@monksbugtracker.com',
            recipient_list=[self.invitee_email]
        )


class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    manager = models.ForeignKey(User, related_name='assigned_projects', on_delete=models.CASCADE, null=True, blank=True)
    is_archived = models.BooleanField(default=False)
    developers = models.ManyToManyField(User, related_name='developer_assigned_projects', blank=True)
    team = models.ForeignKey(Team, related_name='projects', on_delete=models.SET_NULL, null=True)
    subscribers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='project_subscriptions', blank=True)

    objects = models.Manager.from_queryset(ProjectQueryset)()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tracker:project_details', kwargs={'project_pk': self.pk, 'team_slug': self.team.slug})

    def get_description_as_markdown(self):
        return mark_safe(markdown(self.description, extensions=['codehilite', 'fenced_code']))


class Ticket(models.Model):
    # ticket priority constants
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'
    URGENT = 'urgent'
    PRIORITY_CHOICES = [(LOW, 'Low'), (MEDIUM, 'Medium'), (HIGH, 'High'), (URGENT, 'Urgent')]

    # ticket status constants
    OPEN = 'open'
    # ASSIGNED = 'assigned'
    # IN_PROGRESS = 'in_progress'
    CLOSED = 'closed'
    STATUS_CHOICES = ((OPEN, 'Open'), (CLOSED, 'Closed'))

    user = models.ForeignKey(User, related_name='tickets', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    resolution = models.TextField(null=True, default=None, blank=True)
    developer = models.ManyToManyField(User, related_name='assigned_tickets', blank=True)
    project = models.ForeignKey(Project, related_name='project_tickets', on_delete=models.CASCADE)
    priority = models.CharField(choices=PRIORITY_CHOICES, default=LOW, max_length=50)
    status = models.CharField(choices=STATUS_CHOICES, default=OPEN, max_length=50)
    created_on = models.DateTimeField(auto_now_add=True)
    last_updated_on = models.DateTimeField(auto_now=True)
    team = models.ForeignKey(Team, related_name='tickets', on_delete=models.SET_NULL, null=True)
    subscribers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='ticket_subscriptions', blank=True)

    objects = models.Manager.from_queryset(TicketQueryset)()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tracker:ticket_details', kwargs={'pk': self.pk, 'team_slug': self.team.slug})

    def get_description_as_markdown(self):
        return mark_safe(markdown(self.description, extensions=['codehilite', 'fenced_code']))

    def get_resolution_as_markdown(self):
        return mark_safe(markdown(self.resolution, extensions=['codehilite', 'fenced_code']))

    def save(self, *args, **kwargs):
        created = False
        if self.pk == None:
            created = True
        super().save(*args, **kwargs)
        if created:
            email_tuples = []
            team = self.team
            project = self.project
            if self.user in team.members.all():
                notification_preference = self.user.notification_settings.get(

bug_tracker_v2/templates/tracker/OLD_assigned_ticket_list.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        {% if request.user.is_authenticated %}
            <div class="container">
                <h4>My Assigned Tickets</h4>
                <table class="table table-striped table-bordered table-hover table-sm">
                    <thead class="font-weight-bold">
                    <tr>
                        <td>Title</td>
                        <td>Description</td>
                        <td>Developer</td>
                        <td>Project</td>
                        <td>Priority</td>
                        <td>Status</td>
                        <td>Created Date</td>
                        <td>Last Updated</td>
                    </tr>
                    </thead>
                    {% for ticket in tickets_list %}
                    <tr>
                        <td><a href="{% url 'tracker:ticket_details' pk=ticket.pk %}">{{ ticket.title }}</a></td>
                        <td>{{ ticket.description }}</td>
                        <td>
                            {% if ticket.developer.all.count > 0 %}
                                {{ ticket.developer.all|join:", " }}
                            {% else %}
                                None assigned
                            {% endif %}
                        </td>
                        <td>{{ ticket.project }}</td>
                        <td>{{ ticket.priority }}</td>
                        <td>{{ ticket.get_status_display }}</td>
                        <td>{{ ticket.created_on }}</td>
                        <td>{{ ticket.last_updated_on }}</td>
                    </tr>
                    {% empty %}
                        <p>No tickets found.</p>
                    {% endfor %}

                </table>
            </div>
        {% else %}
            <h4>You are not logged in.</h4>
        {% endif %}
    </div>

{% endblock %}

bug_tracker_v2/templates/tracker/create_ticket.html
{% extends 'base.html'%}
{% load static %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block page_javascript %}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
    let simplemde = new SimpleMDE({spellChecker: false,});
</script>
{% endblock %}

{% block page_css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block content %}

<h1>Submit Ticket</h1>

<form method="POST" novalidate>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create">
    {% if project_pk %}
        <a class="btn btn-cancel" href="{% url 'tracker:project_details' project_pk=project_pk team_slug=team_slug %}">Cancel</a>
    {% else %}
        <a class="btn btn-cancel" href="{% url 'tracker:project_list' team_slug=team_slug %}">Cancel</a>
    {% endif %}
</form>

{% endblock %}

bug_tracker_v2/templates/tracker/project_details.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% load bootstrap4 %}
{% load widget_tweaks %}

{% block page_javascript %}
  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
{% endblock page_javascript %}

{% block content %}

        <div class="row">
            <div class="col-md-4">

            <h1>{{ project.title }}</h1>
            <p><strong>Manager: </strong>{{ project.manager }}</p>
            <p>{{ project.get_description_as_markdown }}</p>
            <p><strong>Assigned developers:</strong></p>
            <ul>
                {% for dev in project.developers.all %}
                    <li>{{ dev }}</li>
                {% endfor %}
            </ul>
            {% if user in current_team.get_owners or user == project.manager %}
              <p><a href="{% url 'tracker:project_manage_developers' team_slug=team_slug project_pk=project.pk%}">Manage developers</a></p>
            {% endif %}
            <p>Created on: {{ project.created_on }}</p>
            {% if user in current_team.get_owners or user.is_staff %}

                <div class="row no-gutters">
                <div class="col-md-5">
                    <a class="btn btn-primary" href="{% url 'tracker:project_update' project_pk=project.pk team_slug=team_slug %}">Update Project</a>
                </div>
                <div class="col">
                    <form action="{% url 'tracker:archive_project' project_pk=project.pk team_slug=team_slug %}" method="POST"> {% csrf_token %}
                        <input class="btn btn-warning" type="submit" value="{{ archive_toggle_label }}" onclick="return confirm('{{ archive_toggle_label }}?');">
                    </form>
                </div>
                </div>

            {% endif %}
            <br>
            {% if request.user in project.subscribers.all %}
              <p><a href="{% url 'tracker:unsubscribe_all' team_slug=team_slug project_pk=project.pk %}" data-toggle="tooltip" title="You will no longer receive emails when new tickets are created and you will be unsubscribed from all tickets.">Unsubscribe from project</a></p>
            {% else %}
              <p><a href="{% url 'tracker:subscribe_all' team_slug=team_slug project_pk=project.pk %}" data-toggle="tooltip" title="You will receive emails when new tickets are created and you will be subscribed to all tickets.">Subscribe to project</a></p>
            {% endif %}
            </div>

            <div class="col-md-8">
{#            <div class="row">#}
            {% if ticket_counter > 0 %}
              <div class="row">
                <h3>{{ ticket_table_title }} ({{ ticket_counter }})</h3>
              </div>

                <div class="row">
                  <form class="form-inline" action="" method="GET">
                    <input type="text" class="form-control mb-2 mr-sm-2" placeholder="Title" name="q">

                    <div class="btn-toolbar" role="toolbar">
                      <div class="btn-group mr-2" role="group">
                          <button type="submit" class="btn btn-primary mb-2">Search</button>
                      </div>
                      <div class="btn-group mr-2" role="group">
                          <button class="btn btn-primary mb-2" href="{% url 'tracker:project_details' team_slug=team_slug project_pk=project.pk %}">Reset</button>
                      </div>
                    </div>
                  </form>
                </div>

                <div class="pagination-sm row">
                {% render_table table %}
                </div>
            {% else %}
            <h3>{{ empty_ticket_message }}</h3>
            {% endif %}
{#            </div>#}
                <div class="row">
                    <div class="col">
                        <a href="{% url 'tracker:create_ticket' team_slug=team_slug %}?project={{ project.pk }}" class="btn btn-primary">Submit Ticket</a>
                        <a href="{% url ticket_status_toggle_url project_pk=project.pk team_slug=team_slug %}">{{ ticket_status_toggle }}</a>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

bug_tracker_v2/templates/tracker/project_list.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% load bootstrap4 %}
{#{% load crispy_forms_tags %}#}
{% load widget_tweaks %}

{% block content %}

        {% if request.user.is_authenticated %}
                <h4>Projects ({{ project_count }})</h4>
            {% if project_count > 0 %}
                {% if filter %}
                <form>
                    <div class="card bg-light container mb-3">
                        <div class="card-body row">
                            <div class="form-group col-sm-4 col-md-3">
                                <h5 class="card-title">Title</h5>
                                {% render_field filter.form.title class='form-control' %}
                            </div>
                            <div class="col">
                                <h5 class="card-title">Start Date</h5>
                                {% render_field filter.form.start_date class='form-control' %}
                            </div>
                            <div class="col">
                                <h5 class="card-title">End Date</h5>
                                {% render_field filter.form.end_date class='form-control'%}
                            </div>
                            <div class="col">
                                <h5 class="card-title">Manager</h5>
                                {% render_field filter.form.manager class='form-control' %}
                            </div>
                        </div>
                        <div class="card-body row">
                            <div class="col">
                                <button class="btn btn-primary" type="submit">Search</button>
                                <a href="{% url 'tracker:project_list' team_slug=team_slug %}" class="btn btn-primary">Reset</a>
                            </div>
                            {% if user in current_team.get_owners %}
                                <div class="col text-right">
                                    <a href="{% url 'tracker:create_project' team_slug=team_slug %}" class="btn btn-success">Create New Project</a>
                                </div>
                            {% endif %}
                        </div>
                        </div>
                </form>
                {% endif %}
                {% render_table table %}
            {% else %}
                <h5>{{ empty_project_message }}</h5>
                  {% if user in current_team.get_owners %}
                    <div class="col">
                        <a href="{% url 'tracker:create_project' team_slug=team_slug %}" class="btn btn-success">Create New Project</a>
                    </div>
                  {% endif %}
            {% endif %}

            <a href="{% url archived_view_toggle_url team_slug=team_slug %}">{{ archived_view_toggle }}</a>

        {% else %}
            <h4>You are not logged in.</h4>
        {% endif %}

{% endblock %}

bug_tracker_v2/templates/tracker/project_list_UNUSED_collapsable_search.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block content %}

        {% if request.user.is_authenticated %}
                <h4>Projects</h4>
                {% if filter %}
                <form>
                <div class="accordion" id="searchAccordion">
                    <div class="card bg-light mb-3">
                        <div class="card-header" id="heading">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <h5 style="margin: 0px">Search</h5>
                            </button>
                        </div>
                        <div id="collapseOne" class="collapse" aria-labelledby="heading" data-parent="searchAccordian">
                        <div class="card-body row">
                            <div class="form-group col-sm-4 col-md-3">
                                <h5 class="card-title">Title</h5>
                                {% render_field filter.form.title class='form-control' %}
                            </div>
                            <div class="form-group col-sm-4 col-md-3">
                                <h5 class="card-title">Start Date</h5>
                                {% render_field filter.form.start_date class='form-control' %}
                            </div>
                            <div class="form-group col-sm-4 col-md-3">
                                <h5 class="card-title">End Date</h5>
                                {% render_field filter.form.end_date class='form-control' %}
                            </div>
                            <div class="form-group col-sm-4 col-md-3">
                                <h5 class="card-title">Manager</h5>
                                {% render_field filter.form.manager class='form-control' %}
                            </div>
                            <div class="form-group col-sm-4 col-md-1">
                                <button class="btn btn-primary" type="submit">Search</button>
                            </div>
                            <div class="form-group col-sm-4 col-md-1">
                                <a href="{% url 'tracker:project_list' %}" class="btn btn-primary">Reset</a>
                            </div>

                        </div>
                        </div>
                    </div>
                </div>
                </form>
                {% endif %}
                {% render_table table %}

        {% else %}
            <h4>You are not logged in.</h4>
        {% endif %}

{% endblock %}

bug_tracker_v2/templates/tracker/project_manage_developers.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% load bootstrap4 %}
{% load widget_tweaks %}

{% block content %}

  <h1>{{ project.title }}</h1>
  <h4>Project Developers</h4>
  <ul>
    {% if project_developers.count > 0 %}
      {% for developer in project_developers %}
        <li>{{ developer }} <a href="{% url 'tracker:project_manage_developers' team_slug=team_slug project_pk=project.pk %}?remove={{ developer }}">Remove</a></li>
      {% endfor %}
    {% else %}
      <li>Project has no assigned developers.</li>
    {% endif %}
  </ul>
  <h4>Team Members</h4>
  <ul>
    {% if team_members %}
      {% for member in team_members %}
        <li>{{ member }} <a href="{% url 'tracker:project_manage_developers' team_slug=team_slug project_pk=project.pk %}?add={{ member }}">Add</a></li>
      {% endfor %}
    {% else %}
      <li>No team members to add.</li>
    {% endif %}
  </ul>
  <a href="{% url 'tracker:project_details' team_slug=team_slug project_pk=project.pk %}" class="btn btn-primary">Go back</a>
{% endblock content %}

bug_tracker_v2/templates/tracker/team_update_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block page_javascript %}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
$('textarea').each(function() {
    var simplemde = new SimpleMDE({
        element: this,
        spellChecker: false,
    });
    simplemde.render();
})
</script>
{% endblock %}

{% block page_css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block content %}

<h1>Update Team Description</h1>
<form method="POST" novalidate>
    {% csrf_token %}
    {% bootstrap_form form show_label=False %}
    <input type="submit" value="Update">
    <a href="{% url 'tracker:team_details' team_slug=team_slug %}" class="btn btn-cancel">Cancel</a>
</form>

{% endblock %}