bug_tracker_v2/tracker/urls.py
from django.urls import path
from . import views

app_name = 'tracker'

urlpatterns = [
    path('tickets/', views.TicketTable.as_view(), name='ticket_list'),
    path('tickets/closed/', views.ClosedTicketTable.as_view(), name='closed_ticket_list'),
    path('tickets/assigned/', views.AssignedTicketTable.as_view(), name='assigned_ticket_list'),
    path('tickets/assigned/closed/', views.ClosedAssignedTicketTable.as_view(), name='closed_assigned_ticket_list'),
    path('tickets/create/', views.CreateTicket.as_view(), name='create_ticket'),
    path('tickets/<pk>/', views.SuperTicketDetails.as_view(), name='ticket_details'),
    path('tickets/<pk>/update', views.UpdateTicket.as_view(), name='ticket_update'),
    path('tickets/<pk>/subscribe/', views.SubscribeTicketView.as_view(), name='subscribe_ticket'),
    path('tickets/<pk>/unsubscribe/', views.UnsubscribeTicketView.as_view(), name='unsubscribe_ticket'),
    path('projects/', views.ProjectTable.as_view(), name='project_list'),
    path('projects/archived/', views.ArchivedProjectTable.as_view(), name='archived_project_list'),
    path('archive-project/<project_pk>/', views.ToggleArchiveProject.as_view(), name='archive_project'),
    path('projects/<project_pk>/', views.ProjectDetails.as_view(), name='project_details'),
    path('projects/<project_pk>/update', views.UpdateProject.as_view(), name='project_update'),
    path('projects/<project_pk>/manage-developers/', views.ProjectManageDevelopers.as_view(), name='project_manage_developers'),
    path('projects/<project_pk>/closed_tickets', views.ProjectDetailsClosedTickets.as_view(), name='project_details_closed_tickets'),
    path('projects/<project_pk>/subscribe_to_all/', views.ProjectSubscribeAllTicketsView.as_view(), name='subscribe_all'),
    path('projects/<project_pk>/unsubscribe_to_all/', views.ProjectUnsubscribeAllTicketsView.as_view(),
         name='unsubscribe_all'),
    path('projects/create', views.CreateProject.as_view(), name='create_project'),
    path('delete-comment/<pk>/', views.CommentDelete.as_view(), name='delete_comment'),
    ### Team-related URLs
    path('team_details/', views.TeamDetails.as_view(), name='team_details'),
    path('update/', views.TeamUpdateView.as_view(), name='team_update'),
]

bug_tracker_v2/users/urls.py
from django.urls import path

from bug_tracker_v2.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from .home_view import HomePage
from bug_tracker_v2.tracker.views import (
    TeamDetails, TeamListView, TeamCreateView, TeamAddManager, AcceptTeamInvitation, SendTeamInvitation,
    ManageSubscriptions, MultipleUnsubscribeView, InvitationsListView, DeclineTeamInvitation, ManageNotificationSettings,
    EnableNotificationSetting, DisableNotificationSetting, TeamRemoveManager, TeamAddOwner, ManageTeamOwnership,
    ManageTeamOwnershipWarning, TeamRemoveOwner, TeamRemoveMember, LeaveTeam,
)

from django.urls import reverse

urlpatterns = [
    # path("", HomePage.as_view(), name="home"),
    path("", TeamListView.as_view(), name='home'),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("bug_tracker_v2.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('teams/<slug:team_slug>/', TeamDetails.as_view(), name='team_details'),
    path('teams/<slug:team_slug>/', include('bug_tracker_v2.tracker.urls', namespace='tracker')),
    path('teams/', TeamListView.as_view(), name='team_list'),
    path('create-team/', TeamCreateView.as_view(), name='team_create'),
    path('teams/<slug:team_slug>/leave-team/', LeaveTeam.as_view(), name='leave_team'),
    path('teams/<slug:team_slug>/add-manager/', TeamAddManager.as_view(), name='team_add_manager'),
    path('teams/<slug:team_slug>/remove-manager/', TeamRemoveManager.as_view(), name='team_remove_manager'),
    path('teams/<slug:team_slug>/warning/', ManageTeamOwnershipWarning.as_view(), name='team_ownership_warning'),
    path('teams/<slug:team_slug>/manage-ownership/', ManageTeamOwnership.as_view(), name='manage_team_ownership'),
    path('teams/<slug:team_slug>/add-owner/', TeamAddOwner.as_view(), name='team_add_owner'),
    path('teams/<slug:team_slug>/remove-owner/', TeamRemoveOwner.as_view(), name='team_remove_owner'),
    path('teams/<slug:team_slug>/remove-member/', TeamRemoveMember.as_view(), name='remove_team_member'),
    path('teams/<slug:team_slug>/invite/', SendTeamInvitation.as_view(), name='team_invite'),
    path('accept-invitation/', AcceptTeamInvitation.as_view(), name='accept_team_invitation'),
    path('decline-invitation/', DeclineTeamInvitation.as_view(), name='decline_team_invitation'),
    path('pending-invitations/', InvitationsListView.as_view(), name='pending_invitations'),
    path('my-subscriptions/', ManageSubscriptions.as_view(), name='manage_subscriptions'),
    path('manage-notifications/', ManageNotificationSettings.as_view(), name='manage_notifications'),
    path('disable-notifications/', DisableNotificationSetting.as_view(), name='disable_notification'),
    path('enable-notifications/', EnableNotificationSetting.as_view(), name='enable_notification'),
    path('multiple-unsubscribe/', MultipleUnsubscribeView.as_view(), name='multiple_unsubscribe'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "error-400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "error-403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "error-404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("error-500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bug_tracker_v2/tracker/views.py
from datetime import date, timedelta

from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404
from django.db.models import Count, Q
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import IntegrityError
from django.core.validators import validate_email
from django.core import mail
from django.urls import reverse_lazy, reverse
from django.views import generic, View
from django.template.loader import render_to_string
from django.core import paginator
from django.core.exceptions import PermissionDenied
from django_filters.views import FilterView
from .filters import TicketFilter, ProjectFilter, TicketFilterArchivedProjects
from django_tables2.views import SingleTableMixin, SingleTableView
from . import tables as my_tables

from . import models
from .constants import NOTIFICATION_SETTING_DEFAULTS, NOTIFICATION_SETTING_DESCRIPTIONS
from .forms import CommentForm, CloseTicketResolutionForm, ProjectForm, CreateTicketForm, UpdateTicketForm, TicketFileUploadForm
from .utils import (CommonTemplateContextMixin, ViewTicketMixin, ViewProjectMixin,
                    TeamOwnerMixin, TeamMemberMixin, UpdateTicketMixin, )

from django.contrib.auth import get_user_model

User = get_user_model()

################################################################################ Team-related Views
class TeamDetails(LoginRequiredMixin, TeamMemberMixin, CommonTemplateContextMixin, generic.DetailView):
    model = models.Team
    template_name = 'tracker/team_details.html'
    context_object_name = 'team'
    slug_url_kwarg = 'team_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = self.get_object()
        managers = team.get_managers()
        context['managers'] = managers
        # all_members = team.members.all()
        # non_managers = [user for user in all_members if user not in managers]
        context['non_managers'] = team.get_only_members()
        return context


class TeamUpdateView(LoginRequiredMixin, TeamOwnerMixin, SuccessMessageMixin , CommonTemplateContextMixin, generic.UpdateView):
    model = models.Team
    fields = ['description',]
    template_name = 'tracker/team_update_form.html'
    success_message = 'Team updated.'
    slug_url_kwarg = 'team_slug'


class TeamListView(LoginRequiredMixin, CommonTemplateContextMixin, generic.ListView):
    model = models.Team
    context_object_name = 'teams'
    template_name = 'tracker/team_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if (project_pk:=self.request.user.last_viewed_project_pk):
            last_viewed_project = models.Project.objects.get(pk=project_pk)
            context['last_viewed_project'] = last_viewed_project
        return context

    def get_queryset(self):
        owned_teams = models.Team.objects.user_owned_teams(self.request.user).order_by('title')
        member_teams = models.Team.objects.user_member_teams(self.request.user).order_by('title')
        return {'owned_teams': owned_teams, 'member_teams': member_teams}

class TeamCreateView(LoginRequiredMixin, SuccessMessageMixin, CommonTemplateContextMixin, generic.CreateView):
    model = models.Team
    fields = ['title', 'description']
    template_name = 'tracker/team_create_form.html'
    success_message = '%(title)s created.'

    def form_valid(self, form):
        user = self.request.user
        new_team = form.save()
        models.TeamMembership.objects.create(team=new_team, user=user, role=3)
        return super(TeamCreateView, self).form_valid(form)


class ManageTeamOwnershipWarning(LoginRequiredMixin, TeamOwnerMixin, CommonTemplateContextMixin, generic.DetailView):
    template_name = 'tracker/add_team_owner_warning.html'
    model = models.Team
    slug_url_kwarg = 'team_slug'


class ManageTeamOwnership(LoginRequiredMixin, TeamOwnerMixin, CommonTemplateContextMixin, generic.DetailView):
    template_name = 'tracker/manage_team_ownership.html'
    context_object_name = 'members'
    model = models.Team
    slug_url_kwarg = 'team_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = self.get_object()
        managers = team.get_managers()
        members = team.get_only_members()
        multiple_owners = team.get_owners().count() > 1
        context['valid_members'] = managers|members
        context['multiple_owners'] = multiple_owners
        context['current_owners'] = team.get_owners()
        return context


class TeamAddOwner(LoginRequiredMixin, TeamOwnerMixin, CommonTemplateContextMixin, generic.View):
    def get(self, request, *args, **kwargs):
        team_slug = self.kwargs['team_slug']
        team = models.Team.objects.get(slug=team_slug)
        username = self.request.GET.get('username')
        try:
            user = User.objects.get(username=username)
            if user in team.members.all() or user in team.get_only_members():
                team.add_owner(user)
                messages.success(request, f'{username} added as a co-owner.')
                notification_setting = user.notification_settings.get(
                    'team_role_assignment', NOTIFICATION_SETTING_DEFAULTS.get('team_role_assignment', True)
                )
                if user.email and notification_setting:
                    body = render_to_string('emails/added_as_team_owner.txt', {'team_title': team.title})
                    mail.send_mail(
                        subject=f'Added as co-owner of team {team.title}',
                        message=body,
                        from_email='noreply@monksbugtracker.com',
                        recipient_list=[user.email]
                    )
            else:
                messages.warning(request, 'Cannot make co-owner. User either does not exist or is not a member of your team.')
        except ObjectDoesNotExist:
            messages.warning(request, 'Cannot make co-owner. User either does not exist or is not a member of your team.')
        return redirect(reverse_lazy('team_details', kwargs={'team_slug': team_slug}))


class TeamRemoveOwner(LoginRequiredMixin, TeamOwnerMixin, CommonTemplateContextMixin, generic.View):
    def get(self, request, *args, **kwargs):
        team_slug = self.kwargs['team_slug']
        team = models.Team.objects.get(slug=team_slug)
        user = self.request.user
        if team.remove_owner(user):
            messages.success(request, f'You are no longer an owner of team {team.title}.')
            notification_setting = user.notification_settings.get(
                'team_role_assignment', NOTIFICATION_SETTING_DEFAULTS.get('team_role_assignment', True)
            )
            if user.email and notification_setting:
                body = render_to_string('emails/removed_as_team_owner.txt', {'team_title': team.title})
                mail.send_mail(
                    subject=f'No longer an owner of team {team.title}',
                    message=body,
                    from_email='noreply@monksbugtracker.com',
                    recipient_list=[user.email]
                )
            return HttpResponseRedirect(reverse('team_details', kwargs={'team_slug': team_slug}))
        else:
            messages.warning(request, 'You cannot step down as team owner until you promote a new member as co-owner.')
            return HttpResponseRedirect(reverse('manage_team_ownership', kwargs={'team_slug': team_slug}))


class TeamAddManager(LoginRequiredMixin, TeamOwnerMixin, CommonTemplateContextMixin, generic.View):
    def get(self, request, *args, **kwargs):
        team_slug = self.kwargs['team_slug']
        team = models.Team.objects.get(slug=team_slug)
        username = self.request.GET.get('username')
        try:
            user = User.objects.get(username=username)
            if user in team.members.all():
                team.add_manager(user)
                messages.success(request, f'{username} added as manager.')
                notification_setting = user.notification_settings.get(
                    'team_role_assignment', NOTIFICATION_SETTING_DEFAULTS.get('team_role_assignment', True)
                )
                if user.email and notification_setting:
                    body = render_to_string('emails/added_as_team_manager.txt', {'team_title': team.title})
                    mail.send_mail(
                        subject=f'Added as manager to team {team.title}',
                        message=body,
                        from_email='noreply@monksbugtracker.com',
                        recipient_list=[user.email]
                    )
            else:
                messages.warning(request, 'Cannot make manager. User either does not exist or is not a member of your team.')
        except ObjectDoesNotExist:
            messages.warning(request, 'Cannot make manager. User either does not exist or is not a member of your team.')
        return redirect(reverse_lazy('team_details', kwargs={'team_slug': team_slug}))


class TeamRemoveManager(LoginRequiredMixin, TeamOwnerMixin, CommonTemplateContextMixin, generic.View):
    def get(self, request, *args, **kwargs):
        team_slug = self.kwargs['team_slug']
        team = models.Team.objects.get(slug=team_slug)
        username = self.request.GET.get('username')
        try:
            user = User.objects.get(username=username)
            if user in team.get_managers():
                team.remove_manager(user)
                messages.success(request, f'{username} is no longer a team manager.')
                notification_setting = user.notification_settings.get(

bug_tracker_v2/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Bug Tracker v2{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Bug tracker rebased using Two Scoops methodology and migrated to postgres.">
    <meta name="author" content="Justin Thurman">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}
    {% block page_css %}
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Bug Tracker v2</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
          {% if request.user.is_authenticated %}
              {% if team_slug %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'tracker:ticket_list' team_slug=team_slug %}">All Tickets</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tracker:assigned_ticket_list' team_slug=team_slug %}">My Assigned Tickets</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'tracker:project_list' team_slug=team_slug %}">Projects</a>
                </li>
              {% endif %}
          {% endif %}
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
              {% if user.is_staff %}
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                {% else %}
                <li></li>
              {% endif %}

              {% if team_slug %}
                <li class="nav-item"><a class="nav-link" href="{% url 'team_details' team_slug=team_slug %}">{{ team_name }}</a></li>
              {% endif %}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Welcome, {{ user.name }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                  <a class="dropdown-item" href="{% url 'team_list' %}">My Teams</a>
                  <a class="dropdown-item" href="{% url 'pending_invitations' %}">Pending Invitations ({{ request.user.get_pending_invitations_count }})</a>
                  <a class="dropdown-item" href="{% url 'manage_subscriptions' %}">Subscriptions</a>
                  <a class="dropdown-item" href="{% url 'manage_notifications' %}">Notification Settings</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </div>
              </li>

            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->

{#      <script src="{% static 'js/project.js' %}"></script>#}


    {% endblock javascript %}
    {% block page_javascript %}
    {% endblock %}
  </body>
</html>